### ISSUE TITLE
Problem: do muffins count?

### ISSUE THREAD

**Issue by sromkey** [artefactual-labs/cakematica#2]
There is a rather excellent and easy muffin recipe provided by @sallain 's grandmother but I'm concerned that muffins might be seen as scope creep?

**Comment by Diogenesoftoronto** [comment]
Muffins are like cupcakes which are cakes so...It should be fine :octocat:

**Comment by kellyannewithane** [comment]
Muffins count but only if there are no raisins or bran.  Raisins + bran = yech

**Comment by Diogenesoftoronto** [comment]
Raisins are the best!

**Comment by sallain** [comment]
IMO the spirit of cakematica is what's really important here - if you declare it a treat, then I think it should meet the criteria and be considered for inclusion. Bran is probably a sensible place to draw the line, but raisins are a divisive topic - I think we should permit them as long as the overall baked good tends toward sweet rather than healthful.
